#!/bin/bash
# The logic to start up your application should be put in this
# script. The application will work only if it binds to
# $OPENSHIFT_INTERNAL_IP:8080
#nohup $OPENSHIFT_REPO_DIR/diy/testrubyserver.rb $OPENSHIFT_DIY_IP $OPENSHIFT_REPO_DIR/diy > $OPENSHIFT_DIY_DIR/logs/server.log 2>&1 &

source $OPENSHIFT_DATA_DIR.bash_profile

cd $OPENSHIFT_REPO_DIR

export RACK_ENV=production

bundle exec "rainbows -o $OPENSHIFT_DIY_IP -p $OPENSHIFT_DIY_PORT -c config/rainbows.rb -D"
